# Generated by Django 4.0.2 on 2022-03-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_inventoryitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='content',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_quantity_remaining',
            field=models.IntegerField(default=0.99),
            preserve_default=False,
        ),
    ]
