# Generated by Django 4.0.2 on 2022-03-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_rename_content_inventoryitem_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='content',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_price',
            field=models.FloatField(default=0.99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
