# Generated by Django 4.0.2 on 2022-03-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_rename_content_cartitem_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item_quantity_remaining',
        ),
    ]
